AIDPLANNER/urls.py
from django.contrib import admin
from django.urls import path, include
from AidplannerApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('AidplannerApp/', include('AidplannerApp.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('userlist/', views.UserListView.as_view(), name='userlist'),
    path('user_perm/<int:id>/', views.UserPermSettings.as_view(), name='user_perm'),
]

AidplannerApp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Spot(models.Model):
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('show_detail_spot', kwargs={'id': self.id})

    def get_update_url(self):
        return reverse('update_spot', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('delete_spot', kwargs={'id': self.id})

    name = models.CharField(max_length=64)
    address = models.CharField(max_length=128)
    details = models.TextField(null=True)


class Service(models.Model):
    def __str__(self):
        return self.name

    def get_update_url(self):
        return reverse('update_service', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('delete_service', kwargs={'id': self.id})

    name = models.CharField(max_length=64)
    description = models.CharField(max_length=640)


class Item(models.Model):
    def __str__(self):
        return self.name

    def get_update_url(self):
        return reverse('update_item', kwargs={'id': self.id})

    def get_delete_url(self):
        return reverse('delete_item', kwargs={'id': self.id})

    name = models.CharField(max_length=64)
    description = models.CharField(max_length=360)


class ItemCollection(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=128)
    spot = models.ForeignKey(Spot, on_delete=models.CASCADE, null=True)
    description = models.TextField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    items = models.ManyToManyField(Item, through='ItemCollectionItems')


class ItemCollectionItems(models.Model):

    def __str__(self):
        return self.item.name

    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    itemcollection = models.ForeignKey(ItemCollection, on_delete=models.CASCADE)
    number_needed = models.IntegerField(null=True)
    number_delivered = models.IntegerField(null=True)



class ServiceCollection(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=128)
    spot = models.ForeignKey(Spot, on_delete=models.CASCADE, null=True)
    description = models.TextField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    services = models.ManyToManyField(Service, through='ServiceCollectionServices')


class ServiceCollectionServices(models.Model):

    def __str__(self):
        return self.service.name

    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    servicecollection = models.ForeignKey(ServiceCollection, on_delete=models.CASCADE)
    people_needed = models.IntegerField(null=True)
    hours_needed = models.IntegerField(null=True)

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <title>Document</title>
</head>
<body>
<h1><strong>AID coordinator</strong></h1>
<div class="topnav">
    <a href="{% url 'index' %}">Main Page</a>
    <a href="{% url 'collections' %}">Collections</a>
    <a href="{% url 'stats' %}">Stats</a>
    <a href="{% url 'schedule' %}">Schedule</a>
    <a href="{% url 'userlist' %}">Users</a>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}"> logout</a>
    {% else %}
        <a href="{% url 'login' %}"> login</a>
        <a href="{% url 'register' %}"> register</a>
    {% endif %}
</div>
<p>
    {% block MAINBLOCK %}
        <h1>Main Page</h1>
        <br>
        <p>filler:</p>
        <p>Welcome to AidPlanner, a page made to help to organise Collections of Items, Utilities etc in different spots,<br> as
            well as directing a variety of needed services to different refugee aid centers. <br>Feel free to look around and maybe contribute yourself.</p>

        <p>Future features will include:</p>
        <ul>Ability for users to join and be displayed as "members" of different collections along with their contribution</ul>
        <ul>Abiity to schedule an estimated ETA of arrival of items or people providing service to different spots</ul>
        <ul>Schedule table, with current ETA's of number of specific items arriving to different spots</ul>
        <ul>Statistics shown by spot, to track aid activity over time</ul>
        <ul>Ability to delete items/services from existing collections in edit view</ul>
        <ul>and more</ul>
    {% endblock %}
</p>

<p><img src="{% static 'rzutwieza.jpg' %}" width="400" height="250"></p>
<p>{{ date }}</p>
<p>Currently logged in: {{ user }}</p>
</body>
</html>

templates/collections.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <title>Document</title>
</head>
<body>
<h1><strong>CURRENT COLLECTIONS AND NEEDS</strong></h1>

<div class="topnav">
    <a href="{% url 'index' %}">Main Page</a>
    <a href="{% url 'collections' %}">Collections</a>
    <a href="{% url 'add_collection_item' %}">Add Item Collection</a>
    <a href="{% url 'add_collection_service' %}">Add Service Request</a>
    <a href="{% url 'show_spot' %}">Spots</a>
    <a href="{% url 'item_list' %}">Items</a>
    <a href="{% url 'service_list' %}">Services</a>


</div>


{% block MAINBLOCK %}

{%  endblock %}

<p><img src="{% static 'rzutwieza.jpg' %}" width="400" height="250"> {{ date }}</p>
</body>
</html>

templates/collectionsEXTEN.html
{%  extends 'collections.html' %}
{%  block MAINBLOCK %}
    <h1>Item Collections:</h1>
{% for collection in itemcollections %}
    <p>{{ collection.name }}
        <a href="update_item_collection/{{ collection.id }}/"><button>Edit</button></a>
        <a href="delete_item_collection/{{ collection.id }}/"><button>Delete</button></a></p>
    </p>
    <p>{{ collection.description }}</p>
    <p>{{ collection.spot.name }}</p>
    Items:
    <ul>
    {% for item in collection.itemcollectionitems_set.all %}
    <li>{{ item.item.name }}<br> Items needed: {{ item.number_needed }}<br>Items delivered: {{ item.number_delivered }}</li>
    {% endfor %}
    </ul>
{%  endfor %}
    <h1>Services needed:</h1>
{% for collection in servicecollections %}
    <p>{{ collection.name }}
        <a href="update_service_collection/{{ collection.id }}/"><button>Edit</button></a>
        <a href="delete_service_collection/{{ collection.id }}/"><button>Delete</button></a></p>
    <p>{{ collection.description }}</p>
    <p>{{ collection.spot }}</p>
        Services:
    <ul>
    {% for service in collection.servicecollectionservices_set.all %}
    <li>{{ service.service.name }}<br>People needed: {{ service.people_needed }}<br>Hours needed: {{ service.hours_needed }}</li>
    {% endfor %}
    </ul>
{%  endfor %}
{% endblock %}

templates/edit_service_collection.html
{% extends 'collections.html' %}
{% block MAINBLOCK %}
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}


    <input type="submit">
    </form>
    {% for service_collection_service in servicecollection.servicecollectionservices_set.all %}
    <li><a href={% url 'update_service_in_collection' service_collection_service.id %}>{{ service_collection_service }}</a><br>
        Hours needed: {{ service_collection_service.hours_needed }}<br>
        People needed: {{ service_collection_service.people_needed }}</li>
    {% endfor %}
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% block MAINBLOCK %}
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit">
    </form>
{% endblock %}

templates/form2.html
{% extends 'collections.html' %}
{% block MAINBLOCK %}
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
        {% if items %}
        {% for item in items.all %}
        <p><label>{{ item }}</label>
            <input type="checkbox" name="items" value="{{ item.pk }}" /></p>
        {% endfor %}
        {% endif %}
        {% if services %}
        {% for service in services.all %}
        <p><label>{{ service }}</label>
            <input type="checkbox" name="services" value="{{ service.pk }}" /></p>
        {% endfor %}
        {% endif %}
    <input type="submit">
    </form>
{% endblock %}

{# przekazac kolekcje #}

templates/item_detail_view.html
{% extends 'collections.html' %}
{% block MAINBLOCK %}
    <p>{{ item.name }}</p>
    <p>{{ item.description }}</p>


{% endblock %}

templates/list.html
{#{% extends 'base.html' %}#}
{% extends 'collections.html' %}
{% block MAINBLOCK %}
    <ul>
        {% if spot %}
            <a href={% url 'add_spot' %}> <button>Add new spot</button></a>
        {% endif %}
        {% for item in object_list %}
            <li>
                <a href="{{ item.get_absolute_url }}">{{item}}</a>
                <a href="{{ item.get_update_url }}"> <button>Edytuj</button></a>
                <a href="{{ item.get_delete_url }}"> <button>kasuj</button></a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/manual_form.html
{% extends 'collections.html' %}
{% block MAINBLOCK %}
    <form method="post">
        {% csrf_token %}
        <input type="text" placeholder="name" name="name">
        <input type="text" placeholder="address" name="address">
        <input type="text" placeholder="details" name="details">
        <input type="submit">
    </form>
{% endblock %}

templates/schedule.html
{% extends 'base.html' %}
{% block MAINBLOCK %}

<h1>SCHEDULE kiedys</h1>
    
{% endblock %}

templates/secondaryIndex.html
{% extends 'base.html' %}
{% block MAINBLOCK %}

    <h1> SECONDARY MAIN PAGE </h1>

{% endblock %}

templates/service_list.html
{% extends 'collections.html' %}
{% block MAINBLOCK %}
    <div>
    LISTA USLUG
    wypełniacz


    {% for service in servicelist %}
    <p>
    <div style="border: solid; border-width: 1px;">
        Name: {{ service.name }}<br>
        Description: {{ service.description }}<br>
    </div>
        <a href="{% url 'update_service' service.id %}">Edit Service Type</a>
        <a href="{% url 'delete_service' service.id %}">Delete Service Type</a>
    </p>
    {% endfor %}
    </div>
    <p>Add Service</p>
     <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

templates/spot_detail.html
{% extends 'collections.html' %}
{% block MAINBLOCK %}
    <p>{{ spot.name }}</p>
    <p>{{ spot.address }}</p>
    <p>{{ spot.details }}</p>


{% endblock %}

templates/stats.html
{% extends 'base.html' %}
{% block MAINBLOCK %}

<h1>STATYSTYKI kiedys</h1>

{% endblock %}